name: Flutter Android App Bundle Build and Publish
on:
  workflow_dispatch: # Allows manual triggering of the workflow
jobs:
  flutter_android_bundle_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Ruby for Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
      - name: Get dependencies
        working-directory: ./usr
        run: flutter pub get
      - name: Build Android application
        working-directory: ./usr
        run: flutter build appbundle --release
      - name: Setup Google Play Service Account
        run: |
          echo "${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}" > service-account.json
      - name: Setup Fastlane
        working-directory: ./usr/android
        run: |
          gem install fastlane
          # Create Fastfile if it doesn't exist
          if [ ! -f "fastlane/Fastfile" ]; then
            mkdir -p fastlane
            cat > fastlane/Fastfile << 'EOF'
            default_platform(:android)
            
            platform :android do
              desc "Deploy to Google Play Internal Testing Track"
              lane :deploy_internal do
                upload_to_play_store(
                  track: 'internal',
                  aab: '../build/app/outputs/bundle/release/app-release.aab',
                  json_key: '../../service-account.json',
                  skip_upload_metadata: true,
                  skip_upload_images: true,
                  skip_upload_screenshots: true,
                  release_status: 'completed'
                )
              end
            end
            EOF
          fi
      - name: Deploy to Google Play Internal Testing
        working-directory: ./usr/android
        run: fastlane deploy_internal
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-release-bundle
          path: ./usr/build/app/outputs/bundle/release/*.aab
          retention-days: 7
